// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideogiochiAppApi.Data;

#nullable disable

namespace VideogiochiAppApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240909151849_PrimaMigrazione")]
    partial class PrimaMigrazione
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideogiochiAppApi.Model.Paese", b =>
                {
                    b.Property<int>("IdPaese")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pk_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaese"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaese");

                    b.ToTable("Paese");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.Proprietario", b =>
                {
                    b.Property<int>("IdProprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pk_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProprietario"));

                    b.Property<int?>("Età")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("IdPaese")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaeseIdPaese")
                        .HasColumnType("int");

                    b.HasKey("IdProprietario");

                    b.HasIndex("PaeseIdPaese");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.Videogioco", b =>
                {
                    b.Property<int>("IdVideogioco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Pk_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVideogioco"));

                    b.Property<DateOnly?>("DataDiRilascio")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVideogioco");

                    b.ToTable("Videogioco");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.VideogiocoProprietario", b =>
                {
                    b.Property<int>("IdVideogiocoProprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVideogiocoProprietario"));

                    b.Property<int?>("IdProprietario")
                        .HasColumnType("int");

                    b.Property<int?>("IdVideogioco")
                        .HasColumnType("int");

                    b.Property<int?>("ProprietarioIdProprietario")
                        .HasColumnType("int");

                    b.Property<int?>("VideogiocoIdVideogioco")
                        .HasColumnType("int");

                    b.HasKey("IdVideogiocoProprietario");

                    b.HasIndex("ProprietarioIdProprietario");

                    b.HasIndex("VideogiocoIdVideogioco");

                    b.ToTable("VideogiocoProprietario");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.Proprietario", b =>
                {
                    b.HasOne("VideogiochiAppApi.Model.Paese", "Paese")
                        .WithMany("Proprietario")
                        .HasForeignKey("PaeseIdPaese");

                    b.Navigation("Paese");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.VideogiocoProprietario", b =>
                {
                    b.HasOne("VideogiochiAppApi.Model.Proprietario", "Proprietario")
                        .WithMany("VideogiocoProprietario")
                        .HasForeignKey("ProprietarioIdProprietario");

                    b.HasOne("VideogiochiAppApi.Model.Videogioco", "Videogioco")
                        .WithMany("VideogiocoProprietario")
                        .HasForeignKey("VideogiocoIdVideogioco");

                    b.Navigation("Proprietario");

                    b.Navigation("Videogioco");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.Paese", b =>
                {
                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.Proprietario", b =>
                {
                    b.Navigation("VideogiocoProprietario");
                });

            modelBuilder.Entity("VideogiochiAppApi.Model.Videogioco", b =>
                {
                    b.Navigation("VideogiocoProprietario");
                });
#pragma warning restore 612, 618
        }
    }
}
